apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec-deploy
  namespace: exam-azizbek
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sec-deploy
  template:
    metadata:
      labels:
        app: sec-deploy
    spec:
      containers:
        - name: sec-deploy
          image: m13f13/u-exam-1:v1
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: atanikulov.nvrbckdown.uz/config
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          env:
            - name: CPU
              valueFrom:
                resourceFieldRef:
                  containerName: sec-delpoy
                  resource: requests.cpu
            - name: MEMORY
              valueFrom:
                resourceFieldRef:
                  containerName: sec-deploy
                  resource: requests.memory
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: info
                  key: env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: info
                  key: log_leveI
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: database1
                  key: DB_URI
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: info
                  key: grpc_port
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

